# ====== SOLUSDBOT (Alpha) Configuration ======
safe_mode:
  enabled: true
  lookback_minutes: 30
  vol_warn_pct: 1.2
  vol_panic_pct: 2.0
  widen_factor_warn: 1.2
  widen_factor_panic: 1.8

alpha:
  enabled: true
  box_len: 14
  norm_len: 100
  strong_close: true
  min_box_range_pct: 0.15
  max_box_range_pct: 2.0
  cooloff_seconds: 900
  daily_trade_target: 6

risk:
  max_portfolio_pct: 3.0
  portfolio_usdt_fallback: 10000

pid:
  kp: 0.9
  ki: 0.08
  kd: 0.02
  target_vol_pct: 0.9
  out_min: 0.0
  out_max: 1.0

leverage:
  min: 0.0
  max: 2.5

grid:
  k: 1.0
  levels: 10
  notional_per_side_usdt: 200

daemon:
  loop_seconds: 6
  exponential_backoff_max_s: 60
  max_runtime_seconds: 3540
  sigterm_grace_seconds: 15

datafeed:
  quorum: 1
  divergence_bps: 20

pionex:
  base_url: "https://api.pionex.com"   # aggiorna se diverso
  symbol: "SOL_USDT"
  market: "USDTFUTURE"
  tick_size: null
  step_size: null
  # Header names personalizzabili (se l'API ne usa di diversi)
  key_header: "X-API-KEY"
  sign_header: "X-API-SIGN"
  ts_header: "X-API-TS"
  # Paths endpoint (adattabili in caso di differenze API)
  endpoints:
    market_info: "/api/v1/marketInfo"
    balance: "/api/v1/account"
    open_orders: "/api/v1/orders/open"
    place_order: "/api/v1/order"
    cancel_all: "/api/v1/orders/cancelAll"
    fills: "/api/v1/fills"
