exchange: pionex
base_asset: BTC
quote_asset: USDT

grid:
  min_price: 58000
  max_price: 62000
  levels: 80

trend:
  sma_window: 30
  levels_bull: 100
  levels_bear: 40

risk:
  max_position_usdt: 1500
