safe_mode:
  enabled: true
  lookback_minutes: 30
  vol_warn_pct: 1.2
  vol_panic_pct: 2.0
  widen_factor_warn: 1.2
  widen_factor_panic: 1.8
alpha:
  enabled: true
  box_len: 14
  norm_len: 100
  strong_close: true
  min_box_range_pct: 0.15
  max_box_range_pct: 2.0
  cooloff_seconds: 600
  daily_trade_target: 5
  signal_hysteresis_bars: 2
risk:
  max_portfolio_pct: 3.0
  portfolio_usdt_fallback: 10000
pid:
  kp: 0.9
  ki: 0.08
  kd: 0.02
  target_vol_pct: 0.9
  out_min: 0.0
  out_max: 1.0
leverage:
  min: 0.0
  max: 2.5
grid:
  k: 0.55
  levels: 16
  notional_per_side_usdt: 250
trading:
  mode: grid
  sltp_enabled: true
  sl_buffer_pct: 0.35
  tp_rr: 1.5
  entry_kind: MARKET
  slip_bps: 5
  reduce_only: false
timeframe_auto:
  vol_hi_pct: 1.2
  vol_lo_pct: 0.5
  warmup_trades: 3
  stickiness_loops: 5
daemon:
  loop_seconds: 6
  exponential_backoff_max_s: 60
  max_runtime_seconds: 3540
  sigterm_grace_seconds: 15
datafeed:
  quorum: 1
  divergence_bps: 20
websocket:
  fills_enabled: true
  url: wss://stream.pionex.com/fills
  headers: {}
pionex:
  base_url: https://api.pionex.com
  symbol: SOLUSDT
  market: USDTFUTURE
  tick_size: null
  step_size: null
  key_header: X-API-KEY
  sign_header: X-API-SIGN
  ts_header: X-API-TS
  endpoints:
    market_info: /api/v1/marketInfo
    balance: /api/v1/account
    open_orders: /api/v1/orders/open
    place_order: /api/v1/order
    cancel_all: /api/v1/orders/cancelAll
    cancel_order: /api/v1/order/cancel
    fills: /api/v1/fills
dynamic_sl:
  use_atr: true
  atr_len: 14
  atr_mult: 1.2
  use_box: true
  box_sl_share: 0.5
risk_ladder:
  enabled: true
  win_step_mult: 0.25
  max_mult: 2.0
  loss_reset_mult: 1.0
  loss_penalty_mult: 0.7
  penalty_after_losses: 2
