symbol: SOL_USDT
target_daily_return: 0.01
max_leverage: 2.5
grid_levels: 40
band_k: 3.0
vol_window: 60
max_bp_divergence: 30
uncertainty_vol_threshold: 0.025
resume_vol_threshold: 0.015
allocation_usdt: 300
min_order_usdt: 10
# tick/step: usiamo autodetect; se fallisce, usiamo questi fallback
price_tick_size: 0.001
size_step_size: 0.01
daemon:
  enable: true          # loop continuo
  interval_sec: 60      # quanto attendere tra i cicli (se tutto ok)
  max_runtime_sec: 1500 # runtime massimo per ambienti come GitHub Actions (~25m)
  backoff_initial: 10   # backoff iniziale su errore/sospensione
  backoff_max: 300      # backoff massimo
pid:
  kp: 4.0
  ki: 1.5
  kd: 0.0
  integrator_limit: 0.05
  output_min: 0.0
  output_max: 2.5
safe_mode:
  enable: true
  vol_floor: 0.005
  vol_ceiling: 0.03
  max_penalty: 0.7
logging_level: INFO
