name: Cleanup Old Runs
on:
  schedule:
    - cron: "12 2 * * *"
  workflow_dispatch:
permissions:
  actions: write
  contents: read
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs (keep last 3)
        uses: actions/github-script@v7
        with:
          script: |
            const workflowName = "SOLUSDBOT Live";
            const perPage = 100;
            const { data: workflows } = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const wf = workflows.workflows.find(w => w.name === workflowName);
            if(!wf){ core.setFailed(`Workflow ${workflowName} non trovato`); return; }
            const runs = await github.paginate(
              github.rest.actions.listWorkflowRuns,
              { owner: context.repo.owner, repo: context.repo.repo, workflow_id: wf.id, per_page: perPage }
            );
            runs.sort((a,b)=> new Date(b.created_at) - new Date(a.created_at));
            const toDelete = runs.slice(3);
            for(const r of toDelete){
              await github.rest.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: r.id
              });
              core.info(`Deleted run #${r.run_number} (${r.id})`);
            }
