name: SOLUSDBOT Live
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
concurrency:
  group: solusdbot-live
  cancel-in-progress: true
jobs:
  live:
    runs-on: ubuntu-latest
    timeout-minutes: 62
    env:
      LIVE_MODE: "true"
      PIONEX_API_KEY: ${{ secrets.PIONEX_API_KEY }}
      PIONEX_API_SECRET: ${{ secrets.PIONEX_API_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run daemon
        run: python main.py
      - name: Upload artifacts (state + report + orders)
        uses: actions/upload-artifact@v4
        with:
          name: solusdbot-artifacts
          path: |
            state.json
            report.json
            orders.json
            config.json
          if-no-files-found: ignore
          retention-days: 7
