name: SOLUSDBOT cron

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create config from example (if missing)
        run: |
          if [ ! -f config.yaml ] && [ -f config.example.yaml ]; then cp config.example.yaml config.yaml; fi

      - name: Self-test
        run: python SOLUSDBOT-main/selftest.py

      - name: Run bot
        env:
          PIONEX_API_KEY: ${{ secrets.PIONEX_API_KEY }}
          PIONEX_API_SECRET: ${{ secrets.PIONEX_API_SECRET }}
          DASHBOARD_TOKEN: ${{ secrets.DASHBOARD_TOKEN }}
          LOG_LEVEL: INFO
        run: python -m SOLUSDBOT-main.main || python SOLUSDBOT-main/main.py
