name: SOLUSDBOT cron (robust import)

on:
  workflow_dispatch:
    inputs:
      entrypoint:
        description: 'Script da eseguire (default: SOLUSDBOT-main/main.py)'
        required: false
        default: 'SOLUSDBOT-main/main.py'
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show tree
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f | sort

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create config from example (if missing)
        run: |
          if [ ! -f config.yaml ] && [ -f config.example.yaml ]; then cp config.example.yaml config.yaml; fi

      - name: Resolve entrypoint
        id: ep
        run: |
          EP="${{ github.event.inputs.entrypoint }}"
          if [ -z "$EP" ]; then EP="SOLUSDBOT-main/main.py"; fi
          if [ ! -f "$EP" ]; then echo "ERROR: entrypoint $EP non trovato"; exit 1; fi
          echo "ep=$EP" >> $GITHUB_OUTPUT

      - name: Run bot (adds SOLUSDBOT-main to PYTHONPATH)
        env:
          PIONEX_API_KEY: ${{ secrets.PIONEX_API_KEY }}
          PIONEX_API_SECRET: ${{ secrets.PIONEX_API_SECRET }}
          DASHBOARD_TOKEN: ${{ secrets.DASHBOARD_TOKEN }}
          LOG_LEVEL: INFO
          PYTHONPATH: ${{ github.workspace }}/SOLUSDBOT-main:$PYTHONPATH
        run: |
          python "${{ steps.ep.outputs.ep }}"
