name: SOLUSDBOT live daemon

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"

permissions:
  actions: write
  contents: read

concurrency:
  group: solusdbot-live-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y jq

      - name: Force LIVE mode
        run: echo "LIVE_MODE=true" >> $GITHUB_ENV

      - name: Run bot (daemon-limited)
        env:
          PIONEX_API_KEY: ${{ secrets.PIONEX_API_KEY }}
          PIONEX_API_SECRET: ${{ secrets.PIONEX_API_SECRET }}
          LOG_LEVEL: INFO
        run: python main.py

      - name: Generate report
        if: always()
        env:
          PIONEX_API_KEY: ${{ secrets.PIONEX_API_KEY }}
          PIONEX_API_SECRET: ${{ secrets.PIONEX_API_SECRET }}
          LOG_LEVEL: INFO
        run: python report.py || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: solusdbot-live-artifacts
          path: |
            state.json
            report.json

      - name: Delete older runs (keep only latest)
        if: always()
        run: |
          WF_ID=${{ github.run_id }}
          REPO=${{ github.repository }}
          BRANCH=${{ github.ref_name }}
          echo "Cleaning older runs for $REPO on $BRANCH"
          runs=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"             -H "Accept: application/vnd.github+json"             "https://api.github.com/repos/$REPO/actions/workflows/solusdbot-live.yml/runs?branch=$BRANCH&per_page=50"             | jq -r '.workflow_runs[] | select(.id != '"${{ github.run_id }}"') | .id')
          for rid in $runs; do
            echo "Deleting run $rid"
            curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"               -H "Accept: application/vnd.github+json"               "https://api.github.com/repos/$REPO/actions/runs/$rid" || true
          done
